Cycle through suggestions with tab
britzl/defcon pull request #17
Opened 2024-12-08 15:06 UTC by Jerakin

<tab> now finishes and cycles through commands.

It cycles and suggests up to the next `.`

If you are writing `comm` and press tab it will expand it to `commands` if you tab again (exceed the length of the suggestion list) it will go back to `comm`. 

By not writing anything after the dot we can cycle through the commands within the module. 
https://github.com/user-attachments/assets/8dd2537b-1f36-458d-9ec6-ccc49ff35b3a

2024-12-08 15:07 UTC, Jerakin commented on defcon/html/console_html.lua
> +	return header .. script .. style .. string.format(content, data_list) .. footer
I split up the html content into sub sections. Mainly because there's a lot of `%` which string.format doesn't like.

2024-12-08 22:07 UTC, britzl commented on defcon/html/console_html.lua
> +					}
Indentation

2024-12-08 22:09 UTC, britzl commented on defcon/html/console_html.lua
> +				if (index == null){index=0} else {index = parseInt(index)}
Please format this as a normal multi-line if-else

```
if (index == null) {
    index=0
}
else {
    index = parseInt(index)
}
```

2024-12-08 22:10 UTC, britzl commented on defcon/html/console_html.lua
> +				if (index == null){index=0} else {index = parseInt(index)}
Or as a ternary operator:

```
index = (index != null) ? 0 : parseInt(index)
```

2024-12-08 22:11 UTC, britzl requested changes
Overall good but see comment about indentation and syntax

2024-12-09 10:55 UTC, Jerakin commented
> Overall good but see comment about indentation and syntax

Comments fixed and main merged in to ensure it can be merged back

2024-12-09 12:09 UTC, britzl approved these changes
Thanks!

2024-12-09 12:09 UTC, merged